model:
  target: modules.models.autoencoder.TextureAutoEncoder

# data:
#   target: main.DataModuleFromConfig
#   params:
#     batch_size: 8
#     wrap: True
#     train:
#       target: ldm.data.imagenet.ImageNetSRTrain
#       params:
#         size: 256
#         degradation: pil_nearest
#     validation:
#       target: ldm.data.imagenet.ImageNetSRValidation
#       params:
#         size: 256
#         degradation: pil_nearest

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
